package io.rikka.agent.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * Serializable role enum for chat messages.
 *
 * Identifies the originator of a [ChatMessage] within a [ChatThread].
 *
 * ## Thread safety
 *
 * Enum constants are inherently thread-safe.
 *
 * ## Example
 *
 * ```kotlin
 * val msg = ChatMessage.text("msg-1", ChatRole.User, "Hello!")
 * ```
 */
@Serializable
enum class ChatRole {
    /** A message authored by the human user. */
    User,

    /** A message generated by the AI assistant. */
    Assistant,
}

/**
 * Status of a chat message in its lifecycle.
 *
 * Tracks where a [ChatMessage] is in its generation lifecycle, from
 * initial streaming through to final completion, error, or cancellation.
 *
 * ## Thread safety
 *
 * Enum constants are inherently thread-safe.
 */
@Serializable
enum class MessageStatus {
    /** Message is still being streamed / assembled by the AI model. */
    Streaming,

    /** Message is complete and final -- no further parts will be appended. */
    Final,

    /** Message encountered an error during processing. */
    Error,

    /** Message generation was canceled by the user before completion. */
    Canceled,
}

/**
 * A single message in a chat thread.
 *
 * Each message carries a [role] (user or assistant), an ordered list of
 * structured [parts], and lifecycle metadata ([status], [timestampMs]).
 *
 * ## Backward compatibility
 *
 * Old messages stored with only `content: String` (no `parts`) will be
 * automatically migrated on deserialization: the [parts] list is synthesized
 * as `listOf(Text(content))` when the serialized JSON contains no `parts`
 * field.
 *
 * ## Migration path
 *
 * 1. This class keeps [content] as a read-only derived property so that
 *    existing code doing `message.content` continues to compile.
 * 2. New code should prefer [parts] and use the helper extensions.
 * 3. When persisting to Room, store `parts` as a JSON column (see TypeConverter).
 *    The `content` column can be kept for search / FTS, derived from [textContent].
 *
 * ## Thread safety
 *
 * [ChatMessage] is an immutable data class. All properties are `val` and
 * the [parts] list is structurally shared (read-only). Safe to share across
 * threads without synchronization.
 *
 * ## Example
 *
 * ```kotlin
 * // Create a simple text message
 * val userMsg = ChatMessage.text("msg-1", ChatRole.User, "Show disk usage")
 *
 * // Create a command message with output
 * val cmdMsg = ChatMessage.command(
 *     id = "msg-2",
 *     command = "df -h",
 *     stdout = "Filesystem      Size  Used Avail Use% Mounted on\n/dev/sda1       100G   45G   55G  45% /\n",
 *     exitCode = 0,
 * )
 * ```
 *
 * @property id Unique identifier for this message. Must be unique within
 *   the containing [ChatThread].
 * @property role The originator of this message (user or assistant).
 * @property parts The structured parts of this message. Defaults to an empty
 *   list for backward compatibility with old serialized data that lacks the
 *   `parts` field. When empty and [_content] is non-empty, the [content]
 *   accessor returns [_content]; otherwise it returns [textContent].
 * @property timestampMs Timestamp of this message in milliseconds since the
 *   Unix epoch (UTC).
 * @property status The lifecycle status of this message. Defaults to
 *   [MessageStatus.Final].
 */
@Serializable
data class ChatMessage(
    val id: String,
    val role: ChatRole,
    /**
     * The structured parts of this message.
     *
     * Defaults to a single [MessagePart.Text] wrapping [content] for backward
     * compatibility with old serialized data that lacks the `parts` field.
     */
    val parts: List<MessagePart> = emptyList(),
    val timestampMs: Long,
    val status: MessageStatus = MessageStatus.Final,
    /**
     * Legacy plain-text content field.
     *
     * - On deserialization: if `parts` is empty but `content` is present,
     *   the [ChatMessage] factory auto-migrates to `parts = listOf(Text(content))`.
     * - On access: [content] returns the concatenated text of all [MessagePart.Text]
     *   parts, or empty string if none. This preserves source compatibility for
     *   callers that did `message.content`.
     *
     * **Do not set this directly in new code.** Use [parts] instead.
     */
    @Deprecated("Use parts. Kept for backward-compatible deserialization only.")
    @SerialName("content")
    private val _content: String = "",
) {
    /**
     * Backward-compatible accessor: returns plain-text representation.
     *
     * If [_content] is non-empty (legacy format), returns it directly.
     * Otherwise, returns [textContent] (concatenation of all text parts).
     *
     * For new code, prefer [textContent] or iterate [parts] directly.
     */
    @Suppress("DEPRECATION")
    val content: String
        get() = _content.ifEmpty { textContent }

    /**
     * Concatenated text from all [MessagePart.Text] parts.
     *
     * Joins the text of every [MessagePart.Text] in [parts] with newline
     * separators. Returns an empty string if there are no text parts.
     *
     * @return The combined plain-text content, or `""` if no text parts exist.
     */
    val textContent: String
        get() = parts.filterIsInstance<MessagePart.Text>()
            .joinToString(separator = "\n") { it.text }

    /**
     * All [MessagePart.Command] parts in this message, in order.
     *
     * @return A list of command parts. Empty if the message contains no commands.
     */
    val commands: List<MessagePart.Command>
        get() = parts.filterIsInstance<MessagePart.Command>()

    /**
     * The last [MessagePart.Command] in this message, or `null` if there
     * are no command parts.
     *
     * Useful for quickly checking the most recent command and its exit status.
     *
     * @return The last command part, or `null`.
     */
    val lastCommand: MessagePart.Command?
        get() = commands.lastOrNull()

    /**
     * All stdout parts concatenated into a single string.
     *
     * Joins the text of every [MessagePart.Stdout] in [parts] without
     * separators (stdout chunks already contain their own newlines).
     *
     * @return The combined stdout text, or `""` if no stdout parts exist.
     */
    val stdoutText: String
        get() = parts.filterIsInstance<MessagePart.Stdout>()
            .joinToString(separator = "") { it.text }

    /**
     * All stderr parts concatenated into a single string.
     *
     * Joins the text of every [MessagePart.Stderr] in [parts] without
     * separators (stderr chunks already contain their own newlines).
     *
     * @return The combined stderr text, or `""` if no stderr parts exist.
     */
    val stderrText: String
        get() = parts.filterIsInstance<MessagePart.Stderr>()
            .joinToString(separator = "") { it.text }

    companion object {
        /**
         * Custom JSON instance configured for [MessagePart] polymorphism.
         *
         * Configuration:
         * - `classDiscriminator = "type"` -- uses the `"type"` key for sealed
         *   class polymorphism.
         * - `ignoreUnknownKeys = true` -- tolerates extra fields from newer
         *   serialization formats.
         * - `isLenient = true` -- accepts non-standard JSON (e.g. unquoted keys).
         * - `encodeDefaults = true` -- writes default-valued properties to JSON.
         *
         * Use this for serialization/deserialization of [ChatMessage] and
         * [MessagePart].
         *
         * ## Example
         *
         * ```kotlin
         * val json = """{"id":"m1","role":"User","parts":[{"type":"text","text":"hi"}],"timestampMs":123}"""
         * val msg = ChatMessage.json.decodeFromString<ChatMessage>(json)
         * ```
         */
        val json: Json = Json {
            classDiscriminator = "type"
            ignoreUnknownKeys = true
            isLenient = true
            encodeDefaults = true
        }

        /**
         * Creates a simple text message (convenience factory).
         *
         * Wraps the given [text] string in a single [MessagePart.Text] part.
         *
         * @param id Unique message identifier.
         * @param role The message author ([ChatRole.User] or [ChatRole.Assistant]).
         * @param text The plain-text content.
         * @param timestampMs Message timestamp in epoch milliseconds.
         *   Defaults to the current system time.
         * @param status The message lifecycle status. Defaults to
         *   [MessageStatus.Final].
         * @return A new [ChatMessage] containing a single text part.
         */
        fun text(
            id: String,
            role: ChatRole,
            text: String,
            timestampMs: Long = System.currentTimeMillis(),
            status: MessageStatus = MessageStatus.Final,
        ): ChatMessage = ChatMessage(
            id = id,
            role = role,
            parts = listOf(MessagePart.Text(text)),
            timestampMs = timestampMs,
            status = status,
        )

        /**
         * Creates a command message with its output parts.
         *
         * Builds a [ChatMessage] containing a [MessagePart.Command] and
         * optionally followed by [MessagePart.Stdout] and/or [MessagePart.Stderr]
         * parts. The message role is always [ChatRole.Assistant].
         *
         * @param id Unique message identifier.
         * @param command The shell command string that was executed.
         * @param stdout Standard output from the command. An empty string
         *   (default) means no stdout part is added.
         * @param stderr Standard error from the command. An empty string
         *   (default) means no stderr part is added.
         * @param exitCode The process exit code (0..255), or `null` if the
         *   command is still running. When `null`, the message status is set
         *   to [MessageStatus.Streaming]; when non-null, to [MessageStatus.Final].
         * @param timestampMs Message timestamp in epoch milliseconds.
         *   Defaults to the current system time.
         * @return A new [ChatMessage] with command and output parts.
         */
        fun command(
            id: String,
            command: String,
            stdout: String = "",
            stderr: String = "",
            exitCode: Int? = null,
            timestampMs: Long = System.currentTimeMillis(),
        ): ChatMessage {
            val parts = mutableListOf<MessagePart>()
            parts += MessagePart.Command(command, exitCode)
            if (stdout.isNotEmpty()) parts += MessagePart.Stdout(stdout)
            if (stderr.isNotEmpty()) parts += MessagePart.Stderr(stderr)
            return ChatMessage(
                id = id,
                role = ChatRole.Assistant,
                parts = parts,
                timestampMs = timestampMs,
                status = if (exitCode != null) MessageStatus.Final else MessageStatus.Streaming,
            )
        }
    }
}

/**
 * Aggregated statistics for a chat thread.
 *
 * Computed from the thread's messages. All fields default to zero for
 * backward compatibility with threads that have no stats computed yet.
 *
 * ## Thread safety
 *
 * Immutable data class -- safe to share across threads.
 *
 * @property commandCount Number of user messages (commands executed).
 * @property totalExecutionTimeMs Total wall-clock time between user commands
 *   and their corresponding assistant responses, in milliseconds.
 * @property outputLineCount Total number of lines across all assistant
 *   message content.
 */
@Serializable
data class SessionStats(
    val commandCount: Int = 0,
    val totalExecutionTimeMs: Long = 0,
    val outputLineCount: Int = 0,
) {
    /**
     * Human-readable execution time (e.g. "1m 23s", "45s", "2h 5m").
     */
    val formattedDuration: String
        get() {
            val totalSec = totalExecutionTimeMs / 1000
            val hours = totalSec / 3600
            val minutes = (totalSec % 3600) / 60
            val seconds = totalSec % 60
            return when {
                hours > 0 -> "${hours}h ${minutes}m"
                minutes > 0 -> "${minutes}m ${seconds}s"
                else -> "${seconds}s"
            }
        }
}

/**
 * A chat thread containing an ordered list of messages.
 *
 * Represents a single conversation between a user and the AI assistant.
 * The [messages] list is ordered chronologically (oldest first).
 *
 * ## Thread safety
 *
 * Immutable data class. The [messages] list is read-only (structurally
 * shared). Safe to share across threads.
 *
 * @property id Unique identifier for this thread.
 * @property title Human-readable title for the thread, typically set by the
 *   user or auto-generated from the first message.
 * @property messages Ordered list of messages in this thread (oldest first).
 * @property isPinned Whether this thread is pinned to the top of the list.
 * @property isArchived Whether this thread has been archived (hidden from
 *   the default view).
 * @property tags User-assigned tags for categorization.
 * @property stats Aggregated execution statistics.
 */
@Serializable
data class ChatThread(
    val id: String,
    val title: String,
    val messages: List<ChatMessage>,
    val isPinned: Boolean = false,
    val isArchived: Boolean = false,
    val tags: List<String> = emptyList(),
    val stats: SessionStats = SessionStats(),
)

// ── Backward-compatible deserialization ───────────────────────────────────────

/**
 * Migrates a legacy [ChatMessage] to the parts-based format.
 *
 * If this message already has non-empty [ChatMessage.parts], it is returned
 * unchanged. Otherwise, if the legacy [_content] field is non-empty, a copy
 * is returned with [ChatMessage.parts] set to `listOf(Text(_content))` and
 * the legacy field cleared.
 *
 * Use this for explicit migration scenarios (e.g. Room database migration).
 * For normal deserialization, the default `parts = emptyList()` combined with
 * the `content` accessor handles legacy data automatically.
 *
 * ## Example
 *
 * ```kotlin
 * val migrated = legacyMessage.migrateToParts()
 * require(migrated.parts.isNotEmpty()) { "Migration failed" }
 * ```
 *
 * @return A [ChatMessage] with [ChatMessage.parts] populated. If the message
 *   was already migrated or had no legacy content, returns `this` unchanged.
 */
@Suppress("DEPRECATION")
fun ChatMessage.migrateToParts(): ChatMessage {
    if (parts.isNotEmpty()) return this
    if (_content.isEmpty()) return this
    return copy(
        parts = listOf(MessagePart.Text(_content)),
        _content = "",
    )
}

/**
 * Creates a [MessagePart.Text] from this string.
 *
 * Convenience extension for converting a plain string into a text message part.
 *
 * ## Example
 *
 * ```kotlin
 * val part = "Hello, world!".toTextPart()
 * // part == MessagePart.Text(text = "Hello, world!")
 * ```
 *
 * @return A [MessagePart.Text] containing this string.
 */
fun String.toTextPart(): MessagePart.Text = MessagePart.Text(this)

/**
 * Creates a single-element list containing a [MessagePart.Text] from this string.
 *
 * Convenience extension for converting a plain string into a parts list,
 * useful when building [ChatMessage.parts].
 *
 * ## Example
 *
 * ```kotlin
 * val parts = "Hello!".toTextParts()
 * val msg = ChatMessage("m1", ChatRole.User, parts, System.currentTimeMillis())
 * ```
 *
 * @return A [List] containing a single [MessagePart.Text] with this string.
 */
fun String.toTextParts(): List<MessagePart.Text> = listOf(MessagePart.Text(this))
