package io.rikka.agent.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Polymorphic message part for RikkaAgent.
 *
 * Design principles:
 * - SSH-native: Command, Stdout, Stderr are first-class citizens
 * - AI-friendly: Reasoning, Code support Codex-style JSONL workflows
 * - Extensible: new subtypes can be added without breaking existing serialization
 * - No metadata bag: keep it simple; add later if needed via non-breaking field
 *
 * Serialization uses kotlinx.serialization polymorphism with @SerialName discriminators.
 * The JSON class discriminator is "type" (kotlinx.serialization default for sealed).
 */
@Serializable
sealed class MessagePart {

    // ── SSH-specific ──────────────────────────────────────────────────────────

    /**
     * A command that was (or will be) executed over SSH.
     *
     * @param command The exact command string sent to the remote shell.
     * @param exitCode null while still running; 0..255 after completion.
     * @param startedAtEpochMs Timestamp when execution started (epoch ms).
     */
    @Serializable
    @SerialName("command")
    data class Command(
        val command: String,
        val exitCode: Int? = null,
        val startedAtEpochMs: Long? = null,
    ) : MessagePart() {
        /** Convenience: true when we know the command finished. */
        val isFinished: Boolean get() = exitCode != null

        /** Convenience: true when exit code is 0. */
        val isSuccess: Boolean get() = exitCode == 0
    }

    /**
     * A chunk of stdout produced by a running or finished command.
     *
     * Multiple Stdout parts may appear in sequence to represent streaming output.
     * Renderers should concatenate adjacent Stdout parts for display.
     *
     * @param text The stdout text chunk (may contain newlines).
     */
    @Serializable
    @SerialName("stdout")
    data class Stdout(
        val text: String,
    ) : MessagePart()

    /**
     * A chunk of stderr produced by a running or finished command.
     *
     * @param text The stderr text chunk (may contain newlines).
     */
    @Serializable
    @SerialName("stderr")
    data class Stderr(
        val text: String,
    ) : MessagePart()

    // ── AI / Codex tool integration ───────────────────────────────────────────

    /**
     * A reasoning step from an AI model (e.g. Codex JSONL "reasoning" event).
     *
     * @param text The reasoning text.
     * @param stepId Optional step identifier for correlating with Codex events.
     */
    @Serializable
    @SerialName("reasoning")
    data class Reasoning(
        val text: String,
        val stepId: String? = null,
    ) : MessagePart()

    /**
     * A fenced code block, typically generated by an AI or extracted from output.
     *
     * @param code The raw code content (no fences).
     * @param language Language identifier for syntax highlighting (e.g. "python", "bash").
     *                 null means unknown/auto-detect.
     */
    @Serializable
    @SerialName("code")
    data class Code(
        val code: String,
        val language: String? = null,
    ) : MessagePart()

    // ── General-purpose ───────────────────────────────────────────────────────

    /**
     * Plain text content. The default type for human-readable messages.
     *
     * This is the backward-compatible target: old `ChatMessage(content: String)`
     * migrates to `parts = listOf(Text(content))`.
     *
     * @param text The text content.
     */
    @Serializable
    @SerialName("text")
    data class Text(
        val text: String,
    ) : MessagePart()

    /**
     * An error that occurred during command execution or AI processing.
     *
     * Distinct from Stderr: Stderr is raw stream output; Error is a structured
     * error with a human-readable message and optional cause chain.
     *
     * @param message Human-readable error description.
     * @param cause Optional underlying cause (e.g. exception message).
     * @param code Optional error code (e.g. SSH exit code, HTTP status).
     */
    @Serializable
    @SerialName("error")
    data class Error(
        val message: String,
        val cause: String? = null,
        val code: Int? = null,
    ) : MessagePart()

    // ── Rendering ─────────────────────────────────────────────────────────────

    /**
     * A Mermaid diagram definition for rendering flowcharts, sequence diagrams, etc.
     *
     * @param definition The raw Mermaid DSL (e.g. "graph TD; A-->B;").
     * @param caption Optional caption shown below the rendered diagram.
     */
    @Serializable
    @SerialName("mermaid")
    data class Mermaid(
        val definition: String,
        val caption: String? = null,
    ) : MessagePart()
}
